name: Build and Push to Cachix

on:
  pull_request:
  push:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: dtz-circt
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        cachixArgs: --compression-level 16
    - name: nix flake check
      run: nix flake check --no-update-lock-file

  targets:
    name: build and cache
    strategy:
      fail-fast: false
      matrix:
        attr: [circt, slang]
    needs: flake-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: dtz-circt
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        cachixArgs: --compression-level 16
    - name: Build ${{ matrix.attr }}
      run: nix build -L .#${{ matrix.attr }}
    - name: Run and print version
      run: nix run .#${{ matrix.attr }} -- --version

  devshells:
    runs-on: ubuntu-latest
    needs: flake-check
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: dtz-circt
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        cachixArgs: --compression-level 16
    - name: Build "nix develop circt" profile"
      run: nix develop --profile dev-profile
